### ISSUE TITLE
Play again/press b

### ISSUE THREAD

**Issue by svsjo** [DHBW-Inf20/command-line-tetris#8]
Wenn man b drückt, soll spiel beendet werden und Hauptmenü wieder angezeigt damit man ggf. Erneut spielen kann

**Comment by svsjo** [comment]
> long time no see

Jo Fabi, was geht man! xD
Wie läuft deine T2000? Was macht das Leben? Warum beschäftigtest du doch 2019 mit der Fourier-Transformation, welche auch in der Spracherkennung eine große Rolle spielt?

**Comment by Fabi-02** [comment]
Guten Tag Herr svsjo, mir geht es gut, wie geht es Frau und Kinder?
T2000 habe ich jetzt ein Thema, aber fang da erst nächstes Semester an, weil ich da in ne andere Abteilung komme.
Mein Leben hätte heute lieber Urlaub nehmen sollen. 🍻
Und was macht dein Leben so?
Das Fourier-Transform zeugs war glaube gar nicht 2019 nur da hab ich den Mist auf GitHub hochgeladen.
Von der Mathematik dahinter hatte ich damals keine Ahnung und hab halt nur die Formeln programmiert weil ich fande des richtig satisfying da Animationen zu machen :D
Und wie läuft bei dir T2000 und was hat FT genau mit Spracherkennung zu tun?

**Comment by svsjo** [comment]
Guten Tag @FabiKl, 
T2000 läuft gut, Ausarbeitung in Latex läuft gut(55 Seiten already) und macht Spaß, Fußball läuft gut, Frau hat sich noch nicht gefunden. Von der Adoption von Kindern habe ich vorerst abgesehen.  

Die Fourier-Transformation (konkret die Fast-Fourier-Transformation, welche die Diskrete-Fourier-Transformation mit dynamischer Programmierung umsetzt) bildet das Sprachsignal auf ein Frequenzspektrum ab. Diese ist zur weiteren Verarbeitung mit dem Merkmalsvektoren relevant, aus ihnen kann mehr abgelesen werden als aus dem eigentlichen Signal. Zu genau gehe ich darauf in meiner Ausarbeitung nicht ein, da es sonst zu viel und zu mathematisch wird und ich es vermutlich selbst nicht mehr verstehe.

**Comment by Fabi-02** [comment]
Damit hast du 55 Seiten mehr als ich 😅

**Comment by svsjo** [comment]
Latex einfach so cool wenn man mal drin ist, no joke :D
Und das Thema einfach gut zum schreiben :D
Und somit kann ich mich nächstes Semester zu 90% auf Implementierung in unsere Steuerung kümmern ohne Stress wegen schreiben
Muss ich dich eigentlich taggen @FabiKl oder schaust du einfach öfters mal nach? xD

**Comment by Fabi-02** [comment]
eigentlich egal aber mit taggen seh ich's vlt schneller @svsjo xD

**Comment by svsjo** [comment]
Ja ok, ich mag unsere Chats auf diese Art!!111
@FabiKl

**Comment by Fabi-02** [comment]
definitiv!!! @svsjo

**Comment by svsjo** [comment]
Jetzt gleich um Punkt 15 Uhr Feierabend machen :D
@FabiKl

**Comment by Fabi-02** [comment]
Wann hast du angefangen? xD
@svsjo
